"""Run and validate Phase 11 presentation skin generation."""

from __future__ import annotations

import csv
import hashlib
import json
import platform
from dataclasses import asdict
from importlib.metadata import version
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd
import pyvista as pv
import rasterio
import trimesh
from matplotlib import font_manager
from PIL import Image, ImageDraw, ImageFont

from uqgems.acquisition import sha256
from uqgems.normalization import LOCAL_ORIGIN, TARGET_EPSG
from uqgems.skins import (
    SkinConfig,
    build_skinned_components,
    export_skinned_html,
    export_textured_glb,
    load_skinned_scene_data,
    render_skinned_png,
    save_texture_assets,
)

PHASE11_SCHEMA_VERSION = 3
MATERIAL_REGISTER_FIELDS = (
    "dataset",
    "source_paths",
    "source_sha256",
    "output_path",
    "output_sha256",
    "horizontal_crs",
    "vertical_reference",
    "capture_dates",
    "licence",
    "processing",
    "factuality",
    "validation_status",
    "notes",
)


def _relative(path: Path, root: Path) -> str:
    return str(path.resolve().relative_to(root.resolve())).replace("\\", "/")


def _write_json(path: Path, payload: dict[str, Any]) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, default=str) + "\n", encoding="utf-8")
    return path


def _configuration() -> SkinConfig:
    return SkinConfig()


def _signature(sources: dict[str, Path], config: SkinConfig) -> tuple[str, dict[str, Any]]:
    payload = {
        "schema_version": PHASE11_SCHEMA_VERSION,
        "sources": {name: sha256(path) for name, path in sources.items()},
        "target_epsg": TARGET_EPSG,
        "local_origin": [float(value) for value in LOCAL_ORIGIN],
        "skin_config": asdict(config),
        "source_dates": {
            "orthophoto_capture": "2022-07-24",
            "lidar_capture": "2019",
        },
        "material_policy": {
            "terrain": "factual orthophoto drape",
            "roofs": "factual nadir orthophoto projected by authoritative XY",
            "facades": "schematic procedural texture; not observed facade imagery",
            "utilities": "symbolic display drape; physical depth unknown",
            "geometry_changes": False,
        },
    }
    serialised = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(serialised).hexdigest(), payload


def _material_inventory(root: Path, outputs: dict[str, Path]) -> pd.DataFrame:
    orthophoto_source = (
        root / "data/interim/normalised/context/latest_public_orthophoto_epsg7856.tif"
    )
    return pd.DataFrame(
        [
            {
                "scene_component": "terrain",
                "skin": "2022 Queensland public orthophoto",
                "source": _relative(orthophoto_source, root),
                "output_asset": _relative(outputs["orthophoto_texture"], root),
                "factuality": "observed aerial image",
                "capture_date": "2022-07-24",
                "licence": "Creative Commons Attribution 4.0",
                "limitation": "Visual alignment reference; not survey control.",
            },
            {
                "scene_component": "building roofs",
                "skin": "planar XY projection of 2022 orthophoto",
                "source": _relative(orthophoto_source, root),
                "output_asset": _relative(outputs["orthophoto_texture"], root),
                "factuality": "observed from nadir; geometry remains Phase 7",
                "capture_date": "2022-07-24",
                "licence": "Creative Commons Attribution 4.0",
                "limitation": "May mismatch 2019 LiDAR or changed buildings.",
            },
            {
                "scene_component": "building facades",
                "skin": "procedural panel/window tile",
                "source": "generated by src/uqgems/skins.py",
                "output_asset": _relative(outputs["facade_texture"], root),
                "factuality": "schematic; not observed",
                "capture_date": "not applicable",
                "licence": "project-generated",
                "limitation": "Does not represent actual UQ facade materials or windows.",
            },
            {
                "scene_component": "public utilities",
                "skin": "network colours and symbolic width",
                "source": "data/processed/utilities/uq_pilot_public_utilities.gpkg",
                "output_asset": _relative(outputs["textured_glb"], root),
                "factuality": "horizontal alignment context only",
                "capture_date": "source survey date unknown",
                "licence": "redistribution terms require confirmation",
                "limitation": "Display drape only; physical depth unknown.",
            },
        ]
    )


def _write_mode_viewer(path: Path) -> Path:
    html = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>UQ St Lucia pilot - analysis and presentation skins</title>
<style>
html,body{height:100%;margin:0;font-family:system-ui,sans-serif;background:#18242d;color:#fff}
header{display:flex;gap:.7rem;align-items:center;padding:.7rem 1rem;background:#18242d}
h1{font-size:1rem;margin:0 auto 0 0}.notice{font-size:.78rem;color:#ffd6a0}
button{border:1px solid #aac1ce;border-radius:5px;padding:.5rem .85rem;
background:#2d4655;color:#fff;cursor:pointer}
button.active{background:#fff;color:#173344}
iframe{border:0;width:100%;height:calc(100% - 64px);background:#fff}
</style>
</head>
<body>
<header>
<h1>UQ St Lucia 3D GIS pilot</h1>
<button id="analysis" class="active" onclick="showMode('analysis')">Analysis skin</button>
<button id="presentation" onclick="showMode('presentation')">Presentation skin</button>
<span class="notice">
Orthophoto: 2022 | LiDAR: 2019 | Facades: schematic | Utility depth: unknown |
Queensland public orthophoto: CC BY 4.0
</span>
</header>
<iframe id="viewer" title="UQ pilot 3D viewer" src="uq_pilot_integrated.html"></iframe>
<script>
const files={analysis:'uq_pilot_integrated.html',presentation:'uq_pilot_textured.html'};
function showMode(mode){
 document.getElementById('viewer').src=files[mode];
 for(const key of Object.keys(files)){
   document.getElementById(key).classList.toggle('active',key===mode);
 }
}
</script>
</body>
</html>
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(html, encoding="utf-8")
    return path


def _comparison_figure(analysis_path: Path, presentation_path: Path, output_path: Path) -> Path:
    with Image.open(analysis_path) as source:
        analysis = source.convert("RGB")
    with Image.open(presentation_path) as source:
        presentation = source.convert("RGB")
    height = min(analysis.height, presentation.height)
    if analysis.height != height:
        analysis = analysis.resize((round(analysis.width * height / analysis.height), height))
    if presentation.height != height:
        presentation = presentation.resize(
            (round(presentation.width * height / presentation.height), height)
        )
    banner = 92
    canvas = Image.new("RGB", (analysis.width + presentation.width, height + banner), "white")
    canvas.paste(analysis, (0, banner))
    canvas.paste(presentation, (analysis.width, banner))
    draw = ImageDraw.Draw(canvas)
    title_font = ImageFont.truetype(font_manager.findfont("DejaVu Sans"), 24)
    note_font = ImageFont.truetype(font_manager.findfont("DejaVu Sans"), 17)
    draw.text((18, 10), "Analysis skin", font=title_font, fill="#243447")
    draw.text((analysis.width + 18, 10), "Presentation skin", font=title_font, fill="#243447")
    draw.text(
        (18, 49),
        "Same Phase 7 geometry | Orthophoto 2022 | LiDAR 2019 | Facades schematic",
        font=note_font,
        fill="#8B1E1E",
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    canvas.save(output_path)
    return output_path


def _write_register(
    root: Path,
    sources: dict[str, Path],
    outputs: dict[str, Path],
    status: str,
) -> Path:
    source_paths = ";".join(_relative(path, root) for path in sources.values())
    source_hashes = ";".join(sha256(path) for path in sources.values())
    rows = []
    for name in ("textured_glb", "textured_html", "mode_viewer"):
        path = outputs[name]
        rows.append(
            {
                "dataset": f"Phase 11 {name.replace('_', ' ')}",
                "source_paths": source_paths,
                "source_sha256": source_hashes,
                "output_path": _relative(path, root),
                "output_sha256": sha256(path),
                "horizontal_crs": (
                    f"authoritative EPSG:{TARGET_EPSG}; local-origin presentation coordinates"
                ),
                "vertical_reference": (
                    "terrain/buildings AHD; utilities display-draped with depth unknown"
                ),
                "capture_dates": "LiDAR 2019; orthophoto 2022-07-24",
                "licence": "orthophoto CC BY 4.0; other source terms retained",
                "processing": "planar UV projection and procedural facade tiling",
                "factuality": "terrain/roof imagery observed; facades schematic",
                "validation_status": status,
                "notes": "Presentation derivative only; authoritative Phase 5/7/8 data unchanged.",
            }
        )
    destination = root / "data/material_model_register.csv"
    with destination.open("w", newline="", encoding="utf-8") as stream:
        writer = csv.DictWriter(stream, fieldnames=MATERIAL_REGISTER_FIELDS)
        writer.writeheader()
        writer.writerows(rows)
    return destination


def _software_versions() -> dict[str, str]:
    return {
        "python": platform.python_version(),
        "numpy": np.__version__,
        "pandas": pd.__version__,
        "rasterio": rasterio.__version__,
        "pyvista": pv.__version__,
        "trimesh": trimesh.__version__,
        "pillow": version("pillow"),
        "uqgems": version("uqgems"),
    }


def run_phase11(project_root: str | Path) -> dict[str, Any]:
    """Create and validate switchable analytical and presentation skins."""
    root = Path(project_root).resolve()
    sources = {
        "orthophoto": (
            root / "data/interim/normalised/context/latest_public_orthophoto_epsg7856.tif"
        ),
        "terrain": root / "data/interim/phase5/elevation/dtm_1m.tif",
        "buildings": root / "data/processed/lod2/lod2_buildings.gpkg",
        "building_mesh": root / "data/processed/lod2/uq_pilot_mixed_lod.glb",
        "utilities": root / "data/processed/utilities/uq_pilot_public_utilities.gpkg",
        "analysis_html": root / "reports/scenes/uq_pilot_integrated.html",
        "phase9_summary": root / "reports/tables/phase9_scene.json",
        "phase10_summary": root / "reports/tables/phase10_reproducibility.json",
    }
    missing = [str(path) for path in sources.values() if not path.is_file()]
    if missing:
        raise FileNotFoundError("Phase 11 prerequisites are missing: " + ", ".join(missing))
    phase9 = json.loads(sources["phase9_summary"].read_text(encoding="utf-8"))
    phase10 = json.loads(sources["phase10_summary"].read_text(encoding="utf-8"))
    if phase9.get("status") != "passed" or phase10.get("status") != "passed":
        raise RuntimeError("Phase 9 and Phase 10 validation reports must both pass")

    config = _configuration()
    config.validate()
    signature, signature_payload = _signature(sources, config)
    output_root = root / "data/processed/materials"
    outputs = {
        "manifest": output_root / "phase11_manifest.json",
        "config": output_root / "phase11_skin_config.json",
        "orthophoto_texture": output_root / "orthophoto_texture.jpg",
        "facade_texture": output_root / "procedural_facade_texture.png",
        "textured_glb": output_root / "uq_pilot_textured.glb",
        "textured_html": root / "reports/scenes/uq_pilot_textured.html",
        "mode_viewer": root / "reports/scenes/uq_pilot_skin_viewer.html",
        "plan_figure": root / "reports/figures/phase11_textured_plan.png",
        "oblique_figure": root / "reports/figures/phase11_textured_oblique.png",
        "comparison_figure": root / "reports/figures/phase11_skin_comparison.png",
        "material_inventory": root / "reports/tables/phase11_material_inventory.csv",
        "surface_audit": root / "reports/tables/phase11_building_surface_audit.csv",
        "summary": root / "reports/tables/phase11_skins.json",
    }
    controlled_names = tuple(name for name in outputs if name not in {"manifest", "summary"})
    previous_manifest: dict[str, Any] = {}
    if outputs["manifest"].is_file():
        previous_manifest = json.loads(outputs["manifest"].read_text(encoding="utf-8"))
    recorded = previous_manifest.get("output_sha256", {})
    cache_reused = bool(
        previous_manifest.get("configuration_signature") == signature
        and all(
            outputs[name].is_file()
            and recorded.get(_relative(outputs[name], root)) == sha256(outputs[name])
            for name in controlled_names
        )
    )

    analysis_hash_before = sha256(sources["analysis_html"])
    data = load_skinned_scene_data(root)
    if cache_reused:
        surface_audit = pd.read_csv(outputs["surface_audit"])
    else:
        save_texture_assets(
            data.orthophoto_rgb,
            outputs["orthophoto_texture"],
            outputs["facade_texture"],
            jpeg_quality=config.orthophoto_jpeg_quality,
        )
        with Image.open(outputs["orthophoto_texture"]) as source:
            orthophoto_image = source.convert("RGB")
        with Image.open(outputs["facade_texture"]) as source:
            facade_image = source.convert("RGB")
        components = build_skinned_components(data, config, orthophoto_image, facade_image)
        surface_audit = components.building_surface_audit
        surface_audit.to_csv(outputs["surface_audit"], index=False)
        export_textured_glb(components, outputs["textured_glb"])
        render_skinned_png(
            components,
            outputs["orthophoto_texture"],
            outputs["facade_texture"],
            outputs["plan_figure"],
            camera="plan",
        )
        render_skinned_png(
            components,
            outputs["orthophoto_texture"],
            outputs["facade_texture"],
            outputs["oblique_figure"],
            camera="northeast",
        )
        export_skinned_html(
            components,
            outputs["orthophoto_texture"],
            outputs["facade_texture"],
            outputs["textured_html"],
        )
        _write_mode_viewer(outputs["mode_viewer"])
        _comparison_figure(
            root / "reports/figures/phase9_integrated_oblique.png",
            outputs["oblique_figure"],
            outputs["comparison_figure"],
        )
        inventory = _material_inventory(root, outputs)
        inventory.to_csv(outputs["material_inventory"], index=False)
        _write_json(outputs["config"], signature_payload)

    with rasterio.open(sources["orthophoto"]) as imagery, rasterio.open(
        sources["terrain"]
    ) as terrain:
        imagery_bounds = np.asarray(imagery.bounds, dtype=float)
        terrain_bounds = np.asarray(terrain.bounds, dtype=float)
        imagery_shape = (imagery.height, imagery.width, imagery.count)
        imagery_epsg = imagery.crs.to_epsg() if imagery.crs else None
        imagery_resolution = tuple(float(abs(value)) for value in imagery.res)
    with Image.open(outputs["orthophoto_texture"]) as image:
        orthophoto_size = image.size
        orthophoto_mode = image.mode
    with Image.open(outputs["facade_texture"]) as image:
        facade_size = image.size
        facade_mode = image.mode
    glb_scene = trimesh.load(outputs["textured_glb"], force="scene")
    glb_meshes = list(glb_scene.geometry.values())
    textured_meshes = [
        mesh
        for mesh in glb_meshes
        if getattr(getattr(mesh, "visual", None), "uv", None) is not None
    ]
    source_face_count = sum(len(mesh.faces) for mesh in data.integrated.building_meshes.values())
    assigned_face_count = int(
        surface_audit[["roof_faces", "facade_faces", "base_faces"]].to_numpy().sum()
    )
    roof_uv_min = float(surface_audit["roof_uv_min"].min())
    roof_uv_max = float(surface_audit["roof_uv_max"].max())
    html_text = outputs["textured_html"].read_text(encoding="utf-8", errors="ignore")
    viewer_text = outputs["mode_viewer"].read_text(encoding="utf-8", errors="ignore")
    inventory = pd.read_csv(outputs["material_inventory"])
    original_utilities = data.integrated.utilities
    png_info = {}
    for name in ("plan_figure", "oblique_figure", "comparison_figure"):
        with Image.open(outputs[name]) as image:
            png_info[name] = {
                "width": image.width,
                "height": image.height,
                "bytes": outputs[name].stat().st_size,
            }
    geometry_names = {str(name) for name in glb_scene.geometry}
    checks = {
        "phase9_and_phase10_validation_passed": (
            phase9["status"] == "passed" and phase10["status"] == "passed"
        ),
        "all_source_files_exist": all(path.is_file() for path in sources.values()),
        "orthophoto_is_rgb_epsg7856": (
            imagery_shape == (2000, 2000, 3) and imagery_epsg == TARGET_EPSG
        ),
        "orthophoto_is_25_centimetre_resolution": np.allclose(imagery_resolution, (0.25, 0.25)),
        "orthophoto_and_terrain_bounds_match": np.allclose(
            imagery_bounds, terrain_bounds, atol=0.001
        ),
        "texture_assets_are_valid": (
            orthophoto_size == (2000, 2000)
            and orthophoto_mode == "RGB"
            and facade_size == (512, 512)
            and facade_mode == "RGB"
        ),
        "all_58_buildings_have_surface_audit": len(surface_audit) == 58,
        "every_building_face_is_assigned_once": assigned_face_count == source_face_count,
        "every_building_has_roof_and_facade_faces": bool(
            (surface_audit["roof_faces"] > 0).all()
            and (surface_audit["facade_faces"] > 0).all()
        ),
        "roof_uv_coordinates_stay_inside_orthophoto": (
            roof_uv_min >= -1e-8 and roof_uv_max <= 1.0 + 1e-8
        ),
        "textured_glb_contains_uv_materials": len(textured_meshes) >= 3,
        "textured_glb_retains_full_pilot_bounds": np.allclose(
            glb_scene.bounds[:, :2], np.asarray([[-250.0, -250.0], [250.0, 250.0]]), atol=1.1
        ),
        "textured_glb_contains_symbolic_utilities": any(
            "DISPLAY_ONLY_DEPTH_UNKNOWN" in name for name in geometry_names
        ),
        "source_utilities_remain_2d_and_unknown_depth": (
            not bool(original_utilities.geometry.has_z.any())
            and bool(original_utilities["depth_m"].isna().all())
        ),
        "textured_html_is_self_contained_and_nonempty": (
            outputs["textured_html"].stat().st_size > 1_000_000
            and "vtk" in html_text.lower()
        ),
        "mode_viewer_switches_analysis_and_presentation": all(
            phrase in viewer_text
            for phrase in (
                "Analysis skin",
                "Presentation skin",
                "uq_pilot_integrated.html",
                "uq_pilot_textured.html",
            )
        ),
        "mode_viewer_discloses_temporal_and_semantic_limits": all(
            phrase in viewer_text
            for phrase in (
                "Orthophoto: 2022",
                "LiDAR: 2019",
                "Facades: schematic",
                "depth: unknown",
                "CC BY 4.0",
            )
        ),
        "material_inventory_separates_observed_and_schematic": (
            len(inventory) == 4
            and bool(inventory["factuality"].str.contains("schematic").any())
            and bool(inventory["factuality"].str.contains("observed").any())
        ),
        "orthophoto_attribution_is_recorded": bool(
            inventory["licence"].str.contains("Creative Commons Attribution 4.0").any()
        ),
        "all_fixed_figures_are_nonempty": all(
            info["bytes"] > 25_000 for info in png_info.values()
        ),
        "phase9_analysis_scene_is_unchanged": sha256(sources["analysis_html"])
        == analysis_hash_before,
    }

    status = "passed" if all(checks.values()) else "failed"
    register = _write_register(root, sources, outputs, status)
    summary = {
        "phase": 11,
        "status": status,
        "cache_reused": cache_reused,
        "scope": "presentation skins for the 500 m by 500 m UQ St Lucia pilot",
        "skin_modes": {
            "analysis": "unchanged Phase 9 LoD/confidence colours and GIS interaction",
            "presentation": (
                "2022 orthophoto terrain/roof texture, schematic facades and symbolic utilities"
            ),
        },
        "source_dates": signature_payload["source_dates"],
        "material_policy": signature_payload["material_policy"],
        "coordinate_model": {
            "authoritative_horizontal_crs": f"GDA2020 / MGA zone 56 (EPSG:{TARGET_EPSG})",
            "local_origin": [float(value) for value in LOCAL_ORIGIN],
            "terrain_and_buildings_vertical_reference": "AHD",
            "utility_vertical_reference": "unknown; display drape only",
        },
        "geometry_evidence": {
            "buildings": len(surface_audit),
            "source_faces": source_face_count,
            "assigned_faces": assigned_face_count,
            "roof_faces": int(surface_audit["roof_faces"].sum()),
            "facade_faces": int(surface_audit["facade_faces"].sum()),
            "base_faces": int(surface_audit["base_faces"].sum()),
            "glb_geometry_count": len(glb_meshes),
            "glb_textured_geometry_count": len(textured_meshes),
        },
        "texture_evidence": {
            "orthophoto_pixels": list(orthophoto_size),
            "orthophoto_resolution_m": list(imagery_resolution),
            "orthophoto_bounds": imagery_bounds.tolist(),
            "roof_uv_range": [roof_uv_min, roof_uv_max],
            "facade_texture_pixels": list(facade_size),
        },
        "png_validation": png_info,
        "software": _software_versions(),
        "checks": checks,
        "decision_gate": (
            "The hybrid presentation skin is ready for local demonstration alongside the "
            "unchanged analysis scene. It does not provide observed facade materials or "
            "authoritative utility depths."
        ),
        "limitations": [
            "The 2022 orthophoto and 2019 LiDAR may disagree where the campus changed.",
            "Facade windows and panels are procedural and do not depict actual buildings.",
            "Nadir imagery cannot provide real facade photography.",
            "Roof texture quality is constrained by Phase 7 geometry and source-image visibility.",
            "Public utilities remain sparse, 2D and physical depth is unknown.",
            "Urban Utilities redistribution terms must be confirmed before publication.",
            "The model is not survey-grade or excavation-safe.",
        ],
        "outputs": {
            **{name: _relative(path, root) for name, path in outputs.items()},
            "material_model_register": _relative(register, root),
        },
    }
    _write_json(outputs["summary"], summary)
    output_hashes = {
        _relative(outputs[name], root): sha256(outputs[name]) for name in controlled_names
    }
    manifest = {
        "configuration_signature": signature,
        "signature_inputs": signature_payload,
        "output_sha256": output_hashes,
    }
    if status == "passed":
        _write_json(outputs["manifest"], manifest)
    failed = [name for name, passed in checks.items() if not passed]
    if failed:
        raise RuntimeError(f"Phase 11 validation failed: {', '.join(failed)}")
    return summary


def main() -> int:
    root = Path(__file__).resolve().parents[2]
    summary = run_phase11(root)
    print(f"Phase 11 status: {summary['status']}")
    print(f"Cache reused: {summary['cache_reused']}")
    print(f"Checks passed: {sum(summary['checks'].values())}/{len(summary['checks'])}")
    print(f"Mode viewer: {root / summary['outputs']['mode_viewer']}")
    print(f"Textured GLB: {root / summary['outputs']['textured_glb']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
